### PR TITLE
Accommodate plugins defining a custom changelist.format

### PR DESCRIPTION
**Pull request by jglick**
Port of https://github.com/jenkins-infra/community-functions/pull/22.

### CODE REVIEW

**Review by halkeye — APPROVED** [review]
It looks good, but lemme confirm the tests are calling this function

**Comment by halkeye** [comment]
image

awesome

**Comment by halkeye** [comment]
I'll try to do a release tonight after work, still polishing off the deploy workflow

**Comment by jglick** [comment]
Thanks. No rush on this one.

**Comment by halkeye** [comment]
Okay, builds are going though the pipeline, when https://incrementals.jenkins.io/liveness says 1.2.0 its live

**Pull request merged**
